name: Pyright Lint

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "app/**"
      - "main.py"
      - ".github/workflows/pyright.yml"
      - "pyproject.toml"
      - "uv.lock"

jobs:
  pyright:
    name: Pyright Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v6
        with:
            python-version: "3.13"

      - run: |
          uv sync --all-extras --locked
        shell: bash

      - name: Run Pyright
        uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release
